"use strict";

const express = require("express");
const helmet = require("helmet");
const rateLimit = require("express-rate-limit");
const hpp = require("hpp");
const cors = require("cors");
const compression = require("compression");
const xss = require("xss");
const crypto = require("crypto");
const { logSecurityEvent } = require("../util/auditLogger");
const { logger } = require("../monitoring/metrics");

/**
 * TRIP-MONITORING SECURITY CONFIGURATION
 * ========================================
 *
 * IMPORTANT: This server does NOT generate tokens.
 *
 * Architecture:
 * 1. users_Payment server → Authenticates users, generates encrypted tokens
 * 2. Trip-Monitoring server → Validates tokens, allows access only to authenticated users
 *
 * Token Flow:
 * User (Mobile App)
 *   ↓ [login]
 * users_Payment (generates token)
 *   ↓ [encrypted token returned]
 * Mobile App (stores token)
 *   ↓ [uses token in all requests]
 * Trip-Monitoring (validates token)
 *   ↓ [grants/denies access]
 *
 * This ensures:
 * ✅ Strong authentication (users_Payment responsible)
 * ✅ Token validation (Trip-Monitoring responsible)
 * ✅ NO direct access without valid token
 * ✅ Mobile-app optimized security
 */

// ============================================================================
// 1. TRIP-MONITORING SECURITY CONFIGURATION (Token Validation Only)
// ============================================================================

const tripMonitoringSecurityConfig = {
  // Token Validation (from users_Payment server)
  // These tokens are generated by users_Payment, validated here
  tokenValidationEnabled: process.env.TOKEN_VALIDATION_ENABLED !== "false",
  jwtSecret: process.env.JWT_SECRET,
  encryptionKey: process.env.ENCRYPTION_KEY,

  // Device Identification & Fingerprinting (for tracking)
  deviceFingerprintRequired:
    process.env.DEVICE_FINGERPRINT_REQUIRED !== "false",
  allowNewDevices: process.env.ALLOW_NEW_DEVICES !== "false",
  maxDevicesPerUser: parseInt(process.env.MAX_DEVICES_PER_USER || "5"),

  // Rate Limiting (device-based)
  rateLimitWindow:
    parseInt(process.env.RATE_LIMIT_WINDOW_MOBILE || "15") * 60 * 1000,
  rateLimitMax: parseInt(process.env.RATE_LIMIT_MAX_MOBILE || "200"),
  rateLimitByDevice: process.env.RATE_LIMIT_BY_DEVICE !== "false",

  // SSL/TLS Enforcement
  enforceHttps: process.env.ENFORCE_HTTPS !== "false",
  hsts: {
    maxAge: parseInt(process.env.HSTS_MAX_AGE || "31536000"),
    includeSubDomains: process.env.HSTS_INCLUDE_SUBDOMAINS !== "false",
    preload: process.env.HSTS_PRELOAD !== "false",
  },

  environment: process.env.NODE_ENV || "development",
};

// ============================================================================
// 2. TOKEN VALIDATION MIDDLEWARE (Core for Trip-Monitoring)
// ============================================================================

/**
 * CRITICAL: Validate token from users_Payment server
 * This is the gatekeeper - no one gets in without a valid token
 */
const tokenValidationMiddleware = (req, res, next) => {
  // Health checks bypass token validation
  if (req.path.startsWith("/health") || req.path.startsWith("/metrics")) {
    return next();
  }

  try {
    const encryptedToken =
      req.headers["auth-token"] ||
      req.headers["authorization"]?.replace("Bearer ", "");

    if (!encryptedToken) {
      logSecurityEvent({
        ip: req.ip,
        action: "MISSING_AUTH_TOKEN",
        details: {
          url: req.url,
          method: req.method,
          userAgent: req.get("User-Agent"),
        },
      });

      return res.status(401).json({
        error: "Authentication required - token missing",
        code: "MISSING_AUTH_TOKEN",
      });
    }

    // Token will be verified by verifytoken middleware
    // This just ensures token exists
    req.rawToken = encryptedToken;
    next();
  } catch (err) {
    logger.warn("Token validation middleware error", { error: err.message });
    return res.status(401).json({
      error: "Authentication failed",
      code: "AUTHENTICATION_FAILED",
    });
  }
};

// ============================================================================
// 3. DEVICE FINGERPRINTING UTILITIES
// ============================================================================

/**
 * Generate device fingerprint from mobile headers
 * Combines device info to create a unique identifier
 */
const generateDeviceFingerprint = (req) => {
  try {
    const deviceId = req.headers["x-device-id"] || "unknown";
    const userAgent = req.headers["user-agent"] || "unknown";
    const appVersion = req.headers["x-app-version"] || "unknown";
    const platform = req.headers["x-platform"] || "unknown";

    // Create hash from device information
    const fingerprint = crypto
      .createHash("sha256")
      .update(`${deviceId}:${userAgent}:${appVersion}:${platform}`)
      .digest("hex");

    return {
      fingerprint,
      deviceId,
      userAgent,
      appVersion,
      platform,
      generatedAt: new Date().toISOString(),
    };
  } catch (err) {
    logger.error("Device fingerprint generation failed", {
      error: err.message,
    });
    return null;
  }
};

/**
 * Verify device fingerprint consistency
 * Ensures request is from same device throughout session
 */
const verifyDeviceFingerprint = (stored, current) => {
  if (!stored || !current) {
    return false;
  }

  // Check critical identifiers match
  return (
    stored.deviceId === current.deviceId && stored.platform === current.platform
  );
};

// ============================================================================
// 3. REQUEST SIGNING UTILITIES
// ============================================================================

/**
 * Verify request signature for integrity
 * Mobile apps sign requests with their private key
 * @param {string} signature - Request signature from header
 * @param {Buffer} body - Request body
 * @param {string} appSecret - App secret for signature verification
 */
const verifyRequestSignature = (signature, body, appSecret) => {
  try {
    if (!mobileSecurityConfig.requestSigningRequired) {
      return true;
    }

    if (!signature || !appSecret) {
      logger.warn("Missing signature or app secret for verification");
      return false;
    }

    // Expected signature format: HMAC-SHA256(body, appSecret)
    const bodyBuffer = typeof body === "string" ? Buffer.from(body) : body;
    const expectedSignature = crypto
      .createHmac("sha256", appSecret)
      .update(bodyBuffer)
      .digest("hex");

    return crypto.timingSafeEqual(
      Buffer.from(signature),
      Buffer.from(expectedSignature),
    );
  } catch (err) {
    logger.warn("Request signature verification failed", {
      error: err.message,
    });
    return false;
  }
};

/**
 * Verify timestamp is within acceptable window
 * Prevents replay attacks
 */
const verifyTimestamp = (timestamp) => {
  try {
    const requestTime = parseInt(timestamp);
    const currentTime = Date.now();
    const diff = Math.abs(currentTime - requestTime);

    return diff <= mobileSecurityConfig.timestampValidationWindow;
  } catch (err) {
    logger.warn("Timestamp verification failed", { error: err.message });
    return false;
  }
};

// ============================================================================
// 4. APP VERSION VALIDATION
// ============================================================================

const compareVersions = (v1, v2) => {
  const parts1 = v1.split(".").map(Number);
  const parts2 = v2.split(".").map(Number);

  for (let i = 0; i < Math.max(parts1.length, parts2.length); i++) {
    const part1 = parts1[i] || 0;
    const part2 = parts2[i] || 0;

    if (part1 > part2) return 1;
    if (part1 < part2) return -1;
  }

  return 0;
};

const validateAppVersion = (appVersion) => {
  if (!mobileSecurityConfig.versionCheckRequired || !appVersion) {
    return { valid: true, message: "Version check disabled or not provided" };
  }

  // Check if app version is at minimum required version
  const minComparison = compareVersions(
    appVersion,
    mobileSecurityConfig.minAppVersion,
  );

  if (minComparison < 0) {
    return {
      valid: false,
      message: `App version ${appVersion} is below minimum required version ${mobileSecurityConfig.minAppVersion}`,
      requireUpdate: true,
      minVersion: mobileSecurityConfig.minAppVersion,
    };
  }

  // Check if app version is required to be specific version
  if (mobileSecurityConfig.requiredAppVersion) {
    const requiredComparison = compareVersions(
      appVersion,
      mobileSecurityConfig.requiredAppVersion,
    );

    if (requiredComparison !== 0) {
      return {
        valid: false,
        message: `App must be updated to version ${mobileSecurityConfig.requiredAppVersion}`,
        requireUpdate: true,
        requiredVersion: mobileSecurityConfig.requiredAppVersion,
      };
    }
  }

  return { valid: true, message: "App version is valid" };
};

// ============================================================================
// 5. TOKEN MANAGEMENT (Access & Refresh)
// ============================================================================

/**
 * Token rotation middleware
 * Implements sliding window token refresh for mobile apps
 *
 * Mobile apps should:
 * 1. Store access token in memory (not localStorage)
 * 2. Store refresh token in secure device storage (Keychain/Keystore)
 * 3. Request new tokens before expiry
 */
const tokenRotationMiddleware = (req, res, next) => {
  if (!mobileSecurityConfig.tokenRotationEnabled) {
    return next();
  }

  try {
    const tokenAge = req.user?.tokenAge;
    const tokenExpiry = req.user?.tokenExpiry;

    if (!tokenAge || !tokenExpiry) {
      return next();
    }

    // If token is older than 80% of its lifetime, include refresh suggestion
    const expiryThreshold = tokenExpiry * 0.8;
    if (tokenAge > expiryThreshold) {
      res.set("X-Token-Refresh-Suggested", "true");
      res.set("X-New-Access-Token", req.user?.newAccessToken || "");
    }

    next();
  } catch (err) {
    logger.warn("Token rotation check failed", { error: err.message });
    next();
  }
};

// ============================================================================
// 6. CERTIFICATE PINNING VALIDATION
// ============================================================================

const certificatePinningMiddleware = (req, res, next) => {
  if (!mobileSecurityConfig.pinningEnabled) {
    return next();
  }

  try {
    const clientCertificate = req.get("x-client-certificate-hash");

    if (!clientCertificate) {
      if (mobileSecurityConfig.pinningErrorBehavior === "reject") {
        return res.status(403).json({
          error: "Certificate pinning validation failed",
          code: "PINNING_VALIDATION_FAILED",
        });
      }
      logger.warn("Certificate pinning not provided", { ip: req.ip });
      return next();
    }

    const isCertificatePinned = mobileSecurityConfig.pinnedCertificates.some(
      (pinned) => pinned === clientCertificate,
    );

    if (!isCertificatePinned) {
      logSecurityEvent({
        ip: req.ip,
        action: "CERTIFICATE_PINNING_FAILED",
        details: {
          providedHash: clientCertificate,
          url: req.url,
          userAgent: req.get("user-agent"),
        },
      });

      if (mobileSecurityConfig.pinningErrorBehavior === "reject") {
        return res.status(403).json({
          error: "Certificate validation failed",
          code: "INVALID_CERTIFICATE",
        });
      }
    }

    next();
  } catch (err) {
    logger.error("Certificate pinning middleware error", {
      error: err.message,
    });
    if (mobileSecurityConfig.pinningErrorBehavior === "reject") {
      return res.status(500).json({
        error: "Security validation error",
        code: "SECURITY_ERROR",
      });
    }
    next();
  }
};

// ============================================================================
// 7. MOBILE-SPECIFIC MIDDLEWARE SETUP
// ============================================================================

module.exports = (app) => {
  // Disable server fingerprinting
  app.disable("x-powered-by");
  app.set("trust proxy", 1);

  // ========== CRITICAL: TOKEN VALIDATION FIRST ==========
  // This must be early in the middleware chain
  app.use(tokenValidationMiddleware);

  // ========== HTTPS/TLS Configuration ==========
  if (tripMonitoringSecurityConfig.enforceHttps) {
    app.use((req, res, next) => {
      // Allow health checks and metrics on HTTP
      if (req.path.startsWith("/health") || req.path.startsWith("/metrics")) {
        return next();
      }

      if (req.get("X-Forwarded-Proto") !== "https") {
        return res.status(403).json({
          error: "HTTPS required",
          code: "HTTPS_REQUIRED",
        });
      }
      next();
    });
  }

  // ========== Security Headers (Mobile-Optimized) ==========
  app.use(
    helmet({
      contentSecurityPolicy: {
        directives: {
          defaultSrc: ["'self'"],
          scriptSrc: ["'none'"],
          styleSrc: ["'none'"],
          imgSrc: ["'self'", "data:", "https:"],
          connectSrc: ["'self'"],
          frameSrc: ["'none'"],
          objectSrc: ["'none'"],
        },
      },
      hsts: tripMonitoringSecurityConfig.hsts,
      noSniff: true,
      xssFilter: true,
      referrerPolicy: { policy: "no-referrer" },
    }),
  );

  // ========== Device ID Validation ==========
  app.use((req, res, next) => {
    const deviceId = req.get("x-device-id");
    const appVersion = req.get("x-app-version");

    // Validate device ID format
    if (deviceId && !/^[a-f0-9\-]{36,}$/.test(deviceId)) {
      logSecurityEvent({
        ip: req.ip,
        action: "INVALID_DEVICE_ID_FORMAT",
        details: {
          deviceId,
          url: req.url,
        },
      });
      return res.status(400).json({
        error: "Invalid device ID format",
        code: "INVALID_DEVICE_ID",
      });
    }

    // Store device fingerprint in request
    if (tripMonitoringSecurityConfig.deviceFingerprintRequired && deviceId) {
      req.deviceFingerprint = generateDeviceFingerprint(req);
    }

    next();
  });

  // ========== JSON Parsing ==========
  app.use(
    express.json({
      limit: "5mb",
      verify: (req, res, buf) => {
        req.rawBody = buf;
      },
    }),
  );

  app.use(
    express.urlencoded({
      extended: true,
      limit: "1mb",
      parameterLimit: 50,
    }),
  );

  // ========== MOBILE-APP-ONLY ACCESS ENFORCEMENT ==========
  // ✅ Block browsers, Postman, Insomnia, curl (unless from localhost)
  app.use((req, res, next) => {
    // Allow localhost/internal for development
    const clientIp = req.ip || req.connection.remoteAddress;
    const isLocal =
      clientIp === "127.0.0.1" ||
      clientIp === "::1" ||
      clientIp.includes("192.168.") ||
      clientIp.includes("10.");

    if (isLocal) {
      return next();
    }

    // Health checks always allowed
    if (req.path.startsWith("/health") || req.path.startsWith("/metrics")) {
      return next();
    }

    // ❌ Block browser navigation attempts
    const isBrowserNav =
      req.headers["sec-fetch-dest"] === "document" ||
      req.headers["sec-fetch-mode"] === "navigate" ||
      (req.headers["accept"] && req.headers["accept"].includes("text/html"));

    if (isBrowserNav) {
      logSecurityEvent({
        ip: req.ip,
        action: "BROWSER_ACCESS_BLOCKED",
        details: {
          url: req.url,
          userAgent: req.get("User-Agent"),
        },
      });
      return res.status(403).send("<h1>Access Denied: Mobile App Only</h1>");
    }

    // ❌ Block test tools (Postman, Insomnia, Thunder Client, curl without proper headers)
    const userAgent = req.get("User-Agent") || "";
    const isTestTool =
      userAgent.includes("Postman") ||
      userAgent.includes("Insomnia") ||
      userAgent.includes("Thunder Client") ||
      userAgent.includes("curl");

    const hasMobileHeaders =
      req.get("x-device-id") &&
      (req.get("x-app-version") || req.get("x-platform"));

    if (
      isTestTool &&
      !hasMobileHeaders &&
      process.env.NODE_ENV === "production"
    ) {
      logSecurityEvent({
        ip: req.ip,
        action: "TEST_TOOL_BLOCKED",
        details: {
          tool: userAgent.split("/")[0],
          url: req.url,
        },
      });
      return res.status(403).json({
        error: "Test tools not allowed in production",
        code: "FORBIDDEN_TOOL",
      });
    }

    next();
  });

  // ========== CORS Configuration (Mobile-Only) ==========
  // ✅ STRICT: Only allow mobile app requests
  // ❌ BLOCK: Browser navigation, test tools
  const allowedOrigins = process.env.ALLOWED_ORIGINS
    ? process.env.ALLOWED_ORIGINS.split(",")
    : []; // Empty = no web origins allowed

  app.use(
    cors({
      origin: (origin, callback) => {
        // Allow requests without origin (mobile apps often don't send it)
        if (!origin) {
          return callback(null, true);
        }

        // ✅ Allow listed origins (for web testing if needed)
        if (allowedOrigins.includes(origin)) {
          return callback(null, true);
        }

        // ❌ Block all other origins (browsers, test tools)
        logSecurityEvent({
          ip: "CORS_BLOCKED",
          action: "CORS_ORIGIN_BLOCKED",
          details: { origin },
        });

        callback(new Error("Not allowed by CORS"));
      },
      methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
      allowedHeaders: [
        "Content-Type",
        "Authorization",
        "auth-token",
        "x-device-id",
        "x-app-version",
        "x-platform",
      ],
      credentials: false, // Mobile apps don't use cookies
      maxAge: 3600,
    }),
  );

  // ========== Compression (Important for Mobile) ==========
  // ✅ Reduce response size for mobile bandwidth
  app.use(
    compression({
      level: 6, // Balanced between compression ratio and speed
      threshold: 1024, // Only compress responses > 1KB
      filter: (req, res) => {
        // Don't compress if client says no-compression
        if (req.headers["x-no-compression"]) return false;
        return compression.filter(req, res);
      },
    }),
  );

  // ========== Data Sanitization (Consolidated) ==========
  // ✅ Replace xss-clean and express-mongo-sanitize with robust custom sanitizer
  // This avoids "TypeError: Cannot set property query" in Express 5
  const securitySanitizer = (req, res, next) => {
    const sanitizeRecursive = (obj) => {
      if (typeof obj !== "object" || obj === null) return;

      Object.keys(obj).forEach((key) => {
        // 1. Mongo Injection Protection (Key level)
        let processedKey = key;
        if (key.startsWith("$") || key.includes(".")) {
          processedKey = key.replace(/^\$/, "_").replace(/\./g, "_");
          if (processedKey !== key) {
            obj[processedKey] = obj[key];
            delete obj[key];
            logSecurityEvent({
              ip: req.ip,
              action: "NOSQL_INJECTION_BLOCKED",
              details: { key, url: req.url },
            });
          }
        }

        // 2. XSS Protection (Value level string)
        if (typeof obj[processedKey] === "string") {
          obj[processedKey] = xss(obj[processedKey]);
        }
        // 3. Recursive for nested objects
        else if (
          typeof obj[processedKey] === "object" &&
          obj[processedKey] !== null
        ) {
          sanitizeRecursive(obj[processedKey]);
        }
      });
    };

    if (req.body) sanitizeRecursive(req.body);
    if (req.query) sanitizeRecursive(req.query);
    if (req.params) sanitizeRecursive(req.params);
    next();
  };

  app.use(securitySanitizer);

  app.use(
    hpp({
      whitelist: [
        "sort",
        "fields",
        "page",
        "limit",
        "offset",
        "include",
        "exclude",
        "tripId",
      ],
    }),
  );

  // ========== Rate Limiting (Device-based) ==========
  const mobileRateLimiter = rateLimit({
    windowMs: tripMonitoringSecurityConfig.rateLimitWindow,
    max: tripMonitoringSecurityConfig.rateLimitMax,
    keyGenerator: (req) => {
      return req.get("x-device-id") || req.ip;
    },
    skip: (req) => {
      return req.path.startsWith("/health") || req.path.startsWith("/metrics");
    },
    handler: (req, res) => {
      logger.warn("Rate limit exceeded", {
        ip: req.ip,
        deviceId: req.get("x-device-id"),
        url: req.url,
      });
      res.status(429).json({
        error: "Too many requests",
        code: "RATE_LIMIT_EXCEEDED",
        retryAfter: req.rateLimit.resetTime,
      });
    },
  });

  app.use(mobileRateLimiter);

  // ========== Request Logging (Mobile Specific) ==========
  app.use((req, res, next) => {
    const deviceId = req.get("x-device-id");
    const appVersion = req.get("x-app-version");
    const platform = req.get("x-platform");

    req.mobileContext = {
      deviceId,
      appVersion,
      platform,
    };

    next();
  });

  // ========== Error Handler for Mobile ==========
  app.use((err, req, res, next) => {
    const statusCode = err.status || err.statusCode || 500;
    const errorId = crypto.randomBytes(8).toString("hex");

    if (statusCode >= 400) {
      logSecurityEvent({
        ip: req.ip,
        action: `MOBILE_ERROR_${statusCode}`,
        details: {
          errorId,
          deviceId: req.mobileContext?.deviceId,
          url: req.url,
          method: req.method,
        },
      });
    }

    const response = {
      error: err.message || "An error occurred",
      code: err.code || `ERROR_${statusCode}`,
      errorId,
      timestamp: new Date().toISOString(),
    };

    if (process.env.NODE_ENV !== "development") {
      delete response.stack;
    }

    res.status(statusCode).json(response);
  });

  logger.info("Trip-Monitoring security middleware configured", {
    tokenValidationEnabled: tripMonitoringSecurityConfig.tokenValidationEnabled,
    deviceFingerprintRequired:
      tripMonitoringSecurityConfig.deviceFingerprintRequired,
    httpsEnforced: tripMonitoringSecurityConfig.enforceHttps,
  });
};

// ============================================================================
// EXPORT UTILITIES FOR USE IN ROUTES
// ============================================================================

module.exports.tripMonitoringSecurityConfig = tripMonitoringSecurityConfig;
module.exports.generateDeviceFingerprint = generateDeviceFingerprint;
module.exports.verifyDeviceFingerprint = verifyDeviceFingerprint;
module.exports.tokenValidationMiddleware = tokenValidationMiddleware;
